imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    form:
        resources: ['bootstrap_3_horizontal_layout.html.twig']
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        blackwhitelist: "@blackwhitelist"
        pln_accepting: "%pln_accepting%"
        pln_maxUploadSize: "%pln_maxUploadSize%"
        pln_maxAuSize: "%pln_maxAuSize%"
        pln_uploadChecksumType: "%pln_uploadChecksumType%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
    assets:
        bootstrap_js:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/js/bootstrap.js
        bootstrap_css:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap.css
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap-theme.css
            filters: [cssrewrite]

        bootstrap_glyphicons_ttf:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf
            output: "fonts/glyphicons-halflings-regular.ttf"
        bootstrap_glyphicons_eot:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.eot
            output: "fonts/glyphicons-halflings-regular.eot"
        bootstrap_glyphicons_svg:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.svg
            output: "fonts/glyphicons-halflings-regular.svg"
        bootstrap_glyphicons_woff:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.woff
            output: "fonts/glyphicons-halflings-regular.woff"
        bootstrap_glyphicons_woff2:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2
            output: "fonts/glyphicons-halflings-regular.woff2"

        jquery:
            inputs:
                - %kernel.root_dir%/../vendor/components/jquery/jquery.js
                
# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

monolog:
    use_microseconds: false
    channels: ['sword', 'processing', 'lockss']
    handlers:
        main:
            formatter: monolog.formatter.standard
            max_files: 10
            channels: ['!sword','!processing','!lockss']
        sword:
            type: rotating_file
            channels: ['sword']
            path: "%kernel.logs_dir%/sword.log"
            level: warning
            formatter: monolog.formatter.standard
            max_files: 10
        processing:
            type: rotating_file
            channels: ['processing']
            path: "%kernel.logs_dir%/processing.log"
            level: warning
            formatter: monolog.formatter.standard
            max_files: 10
        lockss:
            type: rotating_file
            channels: ['lockss']
            path: "%kernel.logs_dir%/lockss.log"
            level: warning
            formatter: monolog.formatter.standard
            max_files: 10

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppUserBundle\Entity\User
    from_email:
        address: noreply@pkp-pln.lib.sfu.ca
        sender_name: PKP PLN
    profile:
        form:
            type: appbundle_user_profile
    change_password:
        form:
            type: appbundle_user_password

cl_tissue:
    adapter: clamav

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: dir       # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # bootstrapy pagination
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

ivory_ck_editor:
    input_sync: true
    default_config: pkppln_config
    configs:
        pkppln_config:
            toolbar: standard

